package com.bonnetrouge.toonup.Commons.WackClasses

class UrlGenerator {
	companion object {
		fun generate95(): String {
			val appendix = "plokmijnuhbygvtfcrdxeszwaq:/."
			val builder = StringBuilder()
			builder.append(appendix[15])
			builder.append(appendix[4])
			builder.append(appendix[4])
			builder.append(appendix[9])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[10])
			builder.append(appendix[9])
			builder.append(appendix[7])
			builder.append(appendix[28])
			builder.append(appendix[10])
			builder.append(appendix[24])
			builder.append(appendix[7])
			builder.append(appendix[25])
			builder.append(appendix[2])
			builder.append(appendix[4])
			builder.append(appendix[8])
			builder.append(appendix[8])
			builder.append(appendix[24])
			builder.append(appendix[28])
			builder.append(appendix[4])
			builder.append(appendix[22])
			return builder.toString()
		}
		fun generate14(): String {
			val appendix = "qwertyuiopasdfghjklzxcvbnm:/."
			val builder = StringBuilder()
			builder.append(appendix[15])
			builder.append(appendix[4])
			builder.append(appendix[4])
			builder.append(appendix[9])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[10])
			builder.append(appendix[9])
			builder.append(appendix[7])
			builder.append(appendix[28])
			builder.append(appendix[10])
			builder.append(appendix[24])
			builder.append(appendix[7])
			builder.append(appendix[25])
			builder.append(appendix[2])
			builder.append(appendix[4])
			builder.append(appendix[8])
			builder.append(appendix[8])
			builder.append(appendix[24])
			builder.append(appendix[28])
			builder.append(appendix[4])
			builder.append(appendix[22])
			return builder.toString()
		}
		fun generate40(): String {
			val appendix = "qazwsxedcrfvtgbyhnujmikolp:/."
			val builder = StringBuilder()
			builder.append(appendix[16])
			builder.append(appendix[12])
			builder.append(appendix[12])
			builder.append(appendix[25])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[1])
			builder.append(appendix[25])
			builder.append(appendix[21])
			builder.append(appendix[28])
			builder.append(appendix[1])
			builder.append(appendix[17])
			builder.append(appendix[21])
			builder.append(appendix[20])
			builder.append(appendix[6])
			builder.append(appendix[12])
			builder.append(appendix[23])
			builder.append(appendix[23])
			builder.append(appendix[17])
			builder.append(appendix[28])
			builder.append(appendix[12])
			builder.append(appendix[11])
			return builder.toString()
		}
		fun generate20(): String {
			val appendix = "plqazokmwsxijnedcuhbrfvtg:/."
			val builder = StringBuilder()
			builder.append(appendix[15])
			builder.append(appendix[4])
			builder.append(appendix[4])
			builder.append(appendix[9])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[10])
			builder.append(appendix[9])
			builder.append(appendix[7])
			builder.append(appendix[28])
			builder.append(appendix[10])
			builder.append(appendix[24])
			builder.append(appendix[7])
			builder.append(appendix[25])
			builder.append(appendix[2])
			builder.append(appendix[4])
			builder.append(appendix[8])
			builder.append(appendix[8])
			builder.append(appendix[24])
			builder.append(appendix[28])
			builder.append(appendix[4])
			builder.append(appendix[22])
			return builder.toString()
		}
		fun generate32(): String {
			val appendix = "lkjhgfdsazxcvbnmqwertyuiop:/."
			val builder = StringBuilder()
			builder.append(appendix[15])
			builder.append(appendix[4])
			builder.append(appendix[4])
			builder.append(appendix[9])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[10])
			builder.append(appendix[9])
			builder.append(appendix[7])
			builder.append(appendix[28])
			builder.append(appendix[10])
			builder.append(appendix[24])
			builder.append(appendix[7])
			builder.append(appendix[25])
			builder.append(appendix[2])
			builder.append(appendix[4])
			builder.append(appendix[8])
			builder.append(appendix[8])
			builder.append(appendix[24])
			builder.append(appendix[28])
			builder.append(appendix[4])
			builder.append(appendix[22])
			return builder.toString()
		}
		fun generate54(): String {
			val appendix = "mznxbcvlaksjdhfgqpowieuryt:/."
			val builder = StringBuilder()
			builder.append(appendix[15])
			builder.append(appendix[4])
			builder.append(appendix[4])
			builder.append(appendix[9])
			builder.append(appendix[26])
			builder.append(appendix[27])
			builder.append(appendix[27])
			builder.append(appendix[10])
			builder.append(appendix[9])
			builder.append(appendix[7])
			builder.append(appendix[28])
			builder.append(appendix[10])
			builder.append(appendix[24])
			builder.append(appendix[7])
			builder.append(appendix[25])
			builder.append(appendix[2])
			builder.append(appendix[4])
			builder.append(appendix[8])
			builder.append(appendix[8])
			builder.append(appendix[24])
			builder.append(appendix[28])
			builder.append(appendix[4])
			builder.append(appendix[22])
			return builder.toString()
		}
	}
}
